name             'motd'
maintainer       'Chef Software, Inc'
maintainer_email 'seth@chef.io'
license          'apache2'
description      'Installs/Configures motd'
long_description 'Installs/Configures motd'
version          '0.1.8'
